run:
  timeout: 5m
  go: "1.22"
  skip-dirs:
    - poc
    - vendor

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - gofmt
    - goimports
    - misspell
    - bodyclose
    - noctx
    - gosec
    - exportloopref

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false
  govet:
    check-shadowing: true
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/port402/x402-cli
  misspell:
    locale: US
  gosec:
    excludes:
      - G104  # Audit errors not checked (we use errcheck instead)
      - G304  # File path provided as taint input (acceptable for CLI)

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gosec
        - noctx
    # Exclude test data directories
    - path: testdata/
      linters:
        - all
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
