version: "2"

run:
  timeout: 5m
  go: "1.22"

linters:
  default: none
  enable:
    - govet
    - staticcheck
    - unused
    - ineffassign
    - misspell
  settings:
    staticcheck:
      checks:
        - "all"
        - "-QF*"  # Exclude quickfix suggestions
  exclusions:
    paths:
      - poc
      - vendor

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/port402/x402-cli

output:
  formats:
    text:
      path: stdout
