version: "2"

run:
  timeout: 5m
  go: "1.22"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - misspell
    - bodyclose
    - noctx
    - gosec

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/port402/x402-cli

output:
  formats:
    text:
      path: stdout
